---
- hosts: all
  become: true
  tasks:
  - name: uninstall httpd
    dnf:
      name: httpd
      state: absent
  - name: remove index.html from /var/www/html/
    ansible.builtin.file:
      path: /var/www/html/index.html
      state: absent
  - name: disable HTTP at port 80
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: disabled
  - name: reloading firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded
...
