---
- hosts: all
  become: true
  tasks:
  - name: Install httpd
    dnf:
      name: httpd
      state: latest
  - name: starting httpd
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes
  - name: create index.html at /var/www/html/
    ansible.builtin.copy:
      content: "Welcome to my web server"
      dest: /var/www/html/index.html
      owner: ansible
      group: ansible
  - name: starting firewalld
    ansible.builtin.service:
      name: firewalld
      enabled: yes
      state: started
  - name: enable HTTP at port 80
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: enabled
  - name: reloading firewalld
    ansible.builtin.service:
      name: firewalld
      state: reloaded

...
